[package]
name = "lenia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
fastrand = "2.0.1"
gfx_device_gl = "0.16.2"
piston2d-gfx_graphics = "0.80.0"
piston_window = "*"
